# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-08 22:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Area', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adviser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('extension', models.CharField(blank=True, max_length=12)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Area.Area')),
            ],
        ),
    ]
